version: '3'

tasks:
    setup:
        desc: Setup the project dependencies
        cmds:
            - brew update && brew upgrade
            - command -v protoc &> /dev/null || brew install protobuf
            - brew install swift-protobuf grpc-swift
            - command -v pre-commit &> /dev/null || brew install pre-commit
            - pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install-hooks
    update:
        cmds:
            - pre-commit autoupdate
            - swift package update
            - swift outdated
    lint:
        desc: Lint the project
        cmds:
            - pre-commit run --show-diff-on-failure --color=always --all-files
    generate:
        desc: Generates swift code from the proto files
        cmds:
            - rm -rf tmp
            - mkdir -p tmp
            - protoc --swift_opt=Visibility=public --swift_out=tmp proto/gateway/v1/gateway.proto
            - protoc --grpc-swift_opt=Client=true,Server=false,Visibility=Public --grpc-swift_out=tmp proto/gateway/v1/gateway.proto
            - rm -rf Sources/BaseMindGateway
            - mv tmp/proto/gateway/v1 Sources/BaseMindGateway
            - rm -rf tmp
