name: 'Test'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
env:
    DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}
jobs:
    test:
        runs-on: macos-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup Swift
              uses: swift-actions/setup-swift@v1
            - name: Download the DeepSource CLI
              run: curl https://deepsource.io/cli | sh
            - name: Run tests
              run: swift test --enable-code-coverage
            - name: Create Coverage Report
              uses: maxep/spm-lcov-action@0.3.1
              with:
                  output-file: ./coverage/lcov.info
            - name: Upload Coverage Report
              run: ./bin/deepsource report --analyzer test-coverage --key swift --value-file ./coverage/lcov.info
